# Generated by Django 5.0.6 on 2024-05-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='usuario',
            new_name='user',
        ),
    ]
